# Generated by Django 5.2.16 on 2026-07-12 12:28

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True, null=True, upload_to=course.models.lesson_video_upload_path
            ),
        ),
    ]
