# Generated by Django 5.2.16 on 2026-07-25 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_lesson_video_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_domain",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="course_doma_slug_704eae_idx"),
                    models.Index(
                        fields=["is_active"], name="course_doma_is_acti_15d19e_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="domains",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="course.domain"
            ),
        ),
    ]
