# Generated by Django 5.2.16 on 2026-07-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_domain_course_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="access_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("granted", "Granted"),
                    ("hold", "On Hold"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="access_status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
