# Generated by Django 5.2.16 on 2026-07-30 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_enrollment_access_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
