# Generated by Django 5.2.16 on 2026-07-25 20:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0003_domain_course_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("public", "Public (Homepage)"),
                            ("internal", "Internal (Logged-in Users)"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_users", "All Logged-in Users"),
                            ("specific_course", "Students of a Specific Course"),
                            ("specific_users", "Specific Student(s)"),
                        ],
                        default="all_users",
                        max_length=20,
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pinned announcements always show first",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "publish_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Announcement becomes visible at this time",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional — announcement auto-hides after this time",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="course.course",
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "announcement_announcement",
                "ordering": ["-is_pinned", "-publish_at"],
                "indexes": [
                    models.Index(
                        fields=["announcement_type", "is_active"],
                        name="announcemen_announc_c401d0_idx",
                    ),
                    models.Index(
                        fields=["publish_at"], name="announcemen_publish_05e4ca_idx"
                    ),
                ],
            },
        ),
    ]
