# Generated by Django 5.2.16 on 2026-08-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="is_system_generated",
            field=models.BooleanField(
                default=False,
                help_text="True for notices auto-created by the platform (approvals, grading, etc.) rather than manually written by an admin. Hidden from the main Announcements management list by default.",
            ),
        ),
    ]
