# Generated by Django 5.2.16 on 2026-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0002_announcement_is_system_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
