# Generated by Django 5.2.16 on 2026-07-11 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid 10-digit Indian mobile number.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
