# Generated by Django 5.2.16 on 2026-07-11 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auth_provider",
        ),
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid 10-digit mobile number.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
