# Generated by Django 5.2.16 on 2026-07-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_user_auth_provider_alter_user_contact"),
        ("admin_dashboard", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("active", "Active"),
                    ("revoked", "Revoked"),
                    ("disabled", "Temporarily Disabled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="batch_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="nielit_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="admin_dashboard.centre",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["account_status"], name="accounts_us_account_8a6ddb_idx"
            ),
        ),
    ]
