# Generated by Django 5.2.16 on 2026-07-27 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Centre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("centre_name", models.CharField(max_length=400, unique=True)),
                ("centre_address", models.TextField(blank=True, null=True)),
                (
                    "centre_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "centre_contact",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("centre_desc", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_dashboard_centre",
                "ordering": ["centre_name"],
            },
        ),
    ]
