# Generated by Django 5.2.16 on 2026-08-13 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceMode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="We're currently performing scheduled maintenance. Please check back shortly.",
                        help_text="Shown to visitors on the maintenance page.",
                    ),
                ),
                (
                    "estimated_end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional — shown to visitors as an estimated return time.",
                        null=True,
                    ),
                ),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_dashboard_maintenancemode",
            },
        ),
    ]
