# Generated by Django 5.2.16 on 2026-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="event",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Lower numbers appear first in stacked list / carousel.",
            ),
        ),
    ]
