# Generated by Django 5.2.16 on 2026-07-30 19:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0005_delete_certificate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "header_title",
                    models.CharField(default="NIELIT Delhi", max_length=500),
                ),
                ("header_subtitle", models.CharField(blank=True, max_length=500)),
                (
                    "logo_position",
                    models.CharField(
                        choices=[
                            ("center", "Center"),
                            ("left", "Left"),
                            ("right", "Right"),
                            ("both", "Both Sides"),
                            ("none", "No Logo"),
                        ],
                        default="center",
                        max_length=20,
                    ),
                ),
                (
                    "institute_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "secondary_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                ("logo_size", models.IntegerField(default=80)),
                (
                    "certificate_title",
                    models.CharField(
                        default="CERTIFICATE OF COMPLETION", max_length=200
                    ),
                ),
                ("title_font_size", models.IntegerField(default=28)),
                ("title_color", models.CharField(default="#1e3a8a", max_length=20)),
                (
                    "line_1_text",
                    models.CharField(
                        default="This certificate is proudly presented to",
                        max_length=500,
                    ),
                ),
                ("line_2_student_name", models.BooleanField(default=True)),
                ("line_2_custom_text", models.CharField(blank=True, max_length=200)),
                ("line_2_font_size", models.IntegerField(default=32)),
                ("line_2_color", models.CharField(default="#1e3a8a", max_length=20)),
                (
                    "line_3_text",
                    models.CharField(
                        default="for successfully completing the", max_length=500
                    ),
                ),
                ("line_4_show_course", models.BooleanField(default=True)),
                ("line_4_custom_text", models.CharField(blank=True, max_length=200)),
                ("line_4_font_size", models.IntegerField(default=20)),
                ("line_4_color", models.CharField(default="#1e3a8a", max_length=20)),
                ("line_5_date_range", models.BooleanField(default=True)),
                ("line_5_custom_text", models.CharField(blank=True, max_length=200)),
                ("line_5_font_size", models.IntegerField(default=14)),
                ("line_5_color", models.CharField(default="#000000", max_length=20)),
                (
                    "signatory_count",
                    models.IntegerField(
                        choices=[(1, "One Signatory"), (2, "Two Signatories")],
                        default=2,
                    ),
                ),
                (
                    "signature_1_position",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=20,
                    ),
                ),
                ("signature_1_name", models.CharField(blank=True, max_length=200)),
                (
                    "signature_1_designation",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "signature_1_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/signatures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "signature_2_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "signature_2_designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "signature_2_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/signatures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                ("show_certificate_number", models.BooleanField(default=True)),
                ("show_registration_number", models.BooleanField(default=True)),
                ("show_student_id", models.BooleanField(default=True)),
                ("show_issue_date", models.BooleanField(default=True)),
                ("footer_font_size", models.IntegerField(default=9)),
                ("border_color", models.CharField(default="#1e3a8a", max_length=20)),
                ("border_width", models.IntegerField(default=3)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/backgrounds/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("show_qr_code", models.BooleanField(default=True)),
                (
                    "qr_code_position",
                    models.CharField(
                        choices=[
                            ("bottom-left", "Bottom Left"),
                            ("bottom-right", "Bottom Right"),
                            ("bottom-center", "Bottom Center"),
                        ],
                        default="bottom-right",
                        max_length=20,
                    ),
                ),
                ("qr_code_size", models.IntegerField(default=80)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("revoked", "Revoked"),
                            ("denied", "Denied"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue_date",
                    models.DateField(
                        blank=True,
                        help_text="Set automatically when approved",
                        null=True,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issued_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of issuing authority",
                        max_length=100,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="course.course",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certificate.certificatedesign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "certificate_studentcertificate",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="certificate_status_032cf1_idx"
                    )
                ],
                "unique_together": {("user", "course")},
            },
        ),
    ]
