# Generated by Django 5.2.16 on 2026-07-11 14:07

import django.core.validators
import django.db.models.deletion
import user.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrollment_number",
                    models.CharField(editable=False, max_length=13, unique=True),
                ),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "aadhar_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Aadhar number must be exactly 12 digits.",
                                regex="^\\d{12}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "pin_code",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 6-digit PIN code.",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                ("highest_qualification", models.CharField(blank=True, max_length=150)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=user.models.profile_image_upload_path,
                    ),
                ),
                ("profile_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_learnerprofile",
                "indexes": [
                    models.Index(
                        fields=["enrollment_number"],
                        name="user_learne_enrollm_ed11bc_idx",
                    )
                ],
            },
        ),
    ]
