# Generated by Django 5.2.16 on 2026-07-27 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_passwordresetotp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="notifications_last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="learnerprofile",
            index=models.Index(
                fields=["full_name"], name="user_learne_full_na_2bc2c2_idx"
            ),
        ),
    ]
