# Generated by Django 5.2.16 on 2026-07-28 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_learnerprofile_notifications_last_seen_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learnerprofile",
            name="notifications_last_seen_at",
        ),
    ]
