# Generated by Django 5.2.16 on 2026-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_learnerprofile_notifications_last_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="notifications_last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
