# Generated by Django 5.2.16 on 2026-08-06 20:09

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="attachment",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=assignment.models.assignment_attachment_path,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="submission_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=assignment.models.submission_file_path,
            ),
        ),
    ]
